### ISSUE TITLE
CRUD Backend Endpoints

### ISSUE THREAD

**Issue by pmh-only** [pmh-only/ilggo.ga#1]
## accounts
- [x] login & logout 80bf00f
- [x] get account 7b76b6a
- [x] create account 22c3320
- [x] update account a1a62e4

## novels
- [x] list novels 66d9822
- [x] create novel 2c7264a
- [x] get novel 475b756
- [x] update novel 4c2d42c
- [x] delete novel 4809f1e

## communites
- [x] like novels d7b9510
- [x] list comments ad52c23
- [ ] create comment
- [ ] update comment
- [ ] delete comment

**Comment by aNchor-only** [comment]
빨리 완성해 찰싹찰싹

**Comment by pmh-only** [comment]
에반ㄷ

**Comment by aNchor-only** [comment]
흐흐흫ㅎ

**Comment by aNchor-only** [comment]
(?)
